// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: "postgres://70f7cf8274673c85b2af7aaf35e3ac78ec6169bbe9f1d66f4f3548521397f742:sk_p3FtzW5PmuyzOiC5qfgpG@db.prisma.io:5432/postgres?sslmode=require"
  },
});
